pub struct Ansi {
    pub none: &'static str,
    pub bold: &'static str,
    pub italic: &'static str,
    pub underline: &'static str,
    pub blink: &'static str,
    pub strike: &'static str,
    pub fg_black: &'static str,
    pub fg_red: &'static str,
    pub fg_green: &'static str,
    pub fg_yellow: &'static str,
    pub fg_blue: &'static str,
    pub fg_magenta: &'static str,
    pub fg_cyan: &'static str,
    pub fg_white: &'static str,
    pub fg_gray: &'static str,
    pub fg_grey: &'static str,
    pub fg_bright_red: &'static str,
    pub fg_bright_green: &'static str,
    pub fg_bright_yellow: &'static str,
    pub fg_bright_blue: &'static str,
    pub fg_bright_magenta: &'static str,
    pub fg_bright_cyan: &'static str,
    pub fg_bright_white: &'static str,
    pub bg_black: &'static str,
    pub bg_red: &'static str,
    pub bg_green: &'static str,
    pub bg_yellow: &'static str,
    pub bg_blue: &'static str,
    pub bg_magenta: &'static str,
    pub bg_cyan: &'static str,
    pub bg_white: &'static str,
    pub bg_gray: &'static str,
    pub bg_grey: &'static str,
    pub bg_bright_red: &'static str,
    pub bg_bright_green: &'static str,
    pub bg_bright_yellow: &'static str,
    pub bg_bright_blue: &'static str,
    pub bg_bright_magenta: &'static str,
    pub bg_bright_cyan: &'static str,
    pub bg_bright_white: &'static str,
}

impl Ansi {
    pub const BASIC:Ansi = Ansi {
        none: "\x1b[0m",
        bold: "\x1b[1m",
        italic: "\x1b[3m",
        underline: "\x1b[4m",
        blink: "\x1b[5m",
        strike: "\x1b[9m",
        fg_black: "\x1b[30m",
        fg_red: "\x1b[31m",
        fg_green: "\x1b[32m",
        fg_yellow: "\x1b[33m",
        fg_blue: "\x1b[34m",
        fg_magenta: "\x1b[35m",
        fg_cyan: "\x1b[36m",
        fg_white: "\x1b[37m",
        fg_gray: "\x1b[90m",
        fg_grey: "\x1b[90m",
        fg_bright_red: "\x1b[91m",
        fg_bright_green: "\x1b[92m",
        fg_bright_yellow: "\x1b[93m",
        fg_bright_blue: "\x1b[94m",
        fg_bright_magenta: "\x1b[95m",
        fg_bright_cyan: "\x1b[96m",
        fg_bright_white: "\x1b[97m",
        bg_black: "\x1b[40m",
        bg_red: "\x1b[41m",
        bg_green: "\x1b[42m",
        bg_yellow: "\x1b[43m",
        bg_blue: "\x1b[44m",
        bg_magenta: "\x1b[45m",
        bg_cyan: "\x1b[46m",
        bg_white: "\x1b[47m",
        bg_gray: "\x1b[100m",
        bg_grey: "\x1b[1000m",
        bg_bright_red: "\x1b[101m",
        bg_bright_green: "\x1b[102m",
        bg_bright_yellow: "\x1b[103m",
        bg_bright_blue: "\x1b[104m",
        bg_bright_magenta: "\x1b[105m",
        bg_bright_cyan: "\x1b[106m",
        bg_bright_white: "\x1b[107m",
    };
}
/*
        ("bold", "\x1b[1m"),
        ("italic", "\x1b[3m"),
        ("underline", "\x1b[4m"),
        ("blink", "\x1b[5m"),
        ("strike", "\x1b[9m"),
        ("black", "\x1b[30m"),
        ("red", "\x1b[31m"),
        ("green", "\x1b[32m"),
        ("yellow", "\x1b[33m"),
        ("blue", "\x1b[34m"),
        ("magenta", "\x1b[35m"),
        ("cyan", "\x1b[36m"),
        ("white", "\x1b[37m"),
        ("gray", "\x1b[90m"),
        ("grey", "\x1b[90m"),
        ("bright_red", "\x1b[91m"),
        ("bright_green", "\x1b[92m"),
        ("bright_yellow", "\x1b[93m"),
        ("bright_blue", "\x1b[94m"),
        ("bright_magenta", "\x1b[95m"),
        ("bright_cyan", "\x1b[96m"),
        ("bright_white", "\x1b[97m"),
        ("black", "\x1b[40m"),
        ("red", "\x1b[41m"),
        ("green", "\x1b[42m"),
        ("yellow", "\x1b[43m"),
        ("blue", "\x1b[44m"),
        ("magenta", "\x1b[45m"),
        ("cyan", "\x1b[46m"),
        ("white", "\x1b[47m"),
        ("gray", "\x1b[100m"),
        ("grey", "\x1b[1000m"),
        ("bright_red", "\x1b[101m"),
        ("bright_green", "\x1b[102m"),
        ("bright_yellow", "\x1b[103m"),
        ("bright_blue", "\x1b[104m"),
        ("bright_magenta", "\x1b[105m"),
        ("bright_cyan", "\x1b[106m"),
        ("bright_white", "\x1b[107m"),

        */